name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0
    - name: Restore dependencies
      run: dotnet restore ./fetch_info/fetch_info.sln
    - name: Build
      run: dotnet build ./fetch_info/fetch_info.sln --no-restore
