name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore ./fetch_info/fetch_info.sln 
    - name: Build
      run: dotnet build ./fetch_info/fetch_info.sln --no-restore --configuration Release
    - name: Push Github Package
      if: ${{ github.event_name == 'push' }}
      run: dotnet nuget push **\*.nupkg -s https://nuget.pkg.github.com/ferretly/index.json -k ${GITHUB_TOKEN} --skip-duplicate  
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Push NuGet.org Package
    # https://github.com/marketplace/actions/publish-nuget
      if: ${{ github.event_name == 'push' }}
      uses: rohith/publish-nuget@v2
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: FerretlyClient/FerretlyClient.csproj
          PACKAGE_NAME: FerretlyApiClient
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_FORMAT: apiClient_*
